"use client";

import { Check, CreditCard, Download, Sparkles, Zap } from "lucide-react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";

export function BillingPanel(){
  const checkout=async(plan:'pro'|'team')=>{toast.loading('Opening secure checkout…',{id:'checkout'});const response=await fetch('/api/stripe/checkout',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({plan})});const body=await response.json();if(body.url)location.href=body.url;else toast.error(body.error??'Checkout unavailable',{id:'checkout'})};
  return <><section className="mt-7 grid gap-4 lg:grid-cols-[1fr_.7fr]"><Card className="gradient-border p-6"><div className="flex flex-col justify-between gap-5 sm:flex-row"><div><Badge className="border-violet-400/20 bg-violet-500/10 text-violet-300"><Sparkles className="size-3"/> Current plan</Badge><h2 className="mt-4 text-2xl font-semibold">Pro trial</h2><p className="mt-2 text-xs text-muted-foreground">Your trial ends on August 16, 2026.</p></div><div className="sm:text-right"><strong className="text-3xl">$0</strong><span className="text-xs text-muted-foreground"> / trial</span><Button className="mt-4 block" onClick={()=>checkout('pro')}>Keep Pro</Button></div></div><div className="mt-7 grid gap-3 sm:grid-cols-3">{[['Generations','18 / 30','60%'],['Build minutes','146 / 500','29%'],['Storage','0.8 / 10 GB','8%']].map(([label,value,width])=><div className="rounded-xl border border-white/[.06] bg-white/[.025] p-3" key={label}><div className="flex justify-between text-[10px]"><span className="text-muted-foreground">{label}</span><span>{value}</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-white/[.06]"><span className="block h-full rounded-full bg-gradient-to-r from-violet-500 to-cyan-400" style={{width}}/></div></div>)}</div></Card><Card className="p-6"><div className="flex items-center justify-between"><div><h2 className="text-sm font-semibold">Payment method</h2><p className="mt-1 text-[10px] text-muted-foreground">Used after your trial</p></div><CreditCard className="size-4 text-muted-foreground"/></div><div className="mt-6 flex items-center gap-3 rounded-xl border border-white/[.07] bg-white/[.025] p-3"><span className="grid size-9 place-items-center rounded-lg bg-blue-600 text-[9px] font-bold italic text-white">VISA</span><div><p className="text-xs">•••• 4242</p><small className="text-[9px] text-muted-foreground">Expires 12/29</small></div><Button variant="ghost" size="sm" className="ml-auto">Edit</Button></div></Card></section><section className="mt-5"><div className="mb-4"><h2 className="text-sm font-semibold">Compare plans</h2><p className="mt-1 text-xs text-muted-foreground">Change your plan at any time.</p></div><div className="grid gap-4 lg:grid-cols-3">{[
    {name:'Free',price:'$0',items:['3 projects / month','Basic exports','ProjectForge subdomain']},
    {name:'Pro',price:'$19',items:['30 projects / month','All export formats','Custom domains','Version history'],current:true},
    {name:'Team',price:'$49',items:['Unlimited team projects','5 members included','Collaboration','Admin analytics']},
  ].map(plan=><Card className={`p-5 ${plan.current?'border-violet-400/30 bg-violet-500/[.05]':''}`} key={plan.name}><div className="flex justify-between"><h3 className="font-semibold">{plan.name}</h3>{plan.current&&<Badge>Current</Badge>}</div><div className="mt-4"><strong className="text-3xl">{plan.price}</strong><span className="text-xs text-muted-foreground"> / month</span></div><ul className="mt-5 space-y-2.5">{plan.items.map(item=><li className="flex gap-2 text-xs text-muted-foreground" key={item}><Check className="size-3.5 text-emerald-400"/>{item}</li>)}</ul><Button onClick={()=>checkout(plan.name==='Team'?'team':'pro')} disabled={plan.current||plan.name==='Free'} variant={plan.current?'secondary':'outline'} className="mt-6 w-full">{plan.current?'Current plan':plan.name==='Free'?'Included':'Choose plan'}</Button></Card>)}</div></section><Card className="mt-5 overflow-hidden"><div className="flex items-center justify-between border-b p-5"><div><h2 className="text-sm font-semibold">Invoices</h2><p className="mt-1 text-[10px] text-muted-foreground">Download billing receipts.</p></div></div><div className="divide-y divide-white/[.06]">{[['Jul 2, 2026','Pro plan','$19.00'],['Jun 2, 2026','Pro plan','$19.00']].map(([date,label,amount])=><div className="flex items-center gap-4 px-5 py-4 text-xs" key={date}><span className="text-muted-foreground">{date}</span><span className="flex-1">{label}</span><span>{amount}</span><Button variant="ghost" size="icon" className="size-8"><Download/></Button></div>)}</div></Card></>;
}
