"use client";

import { Check, Copy, Github, Globe2, KeyRound, Link2, Lock, Save, ShieldCheck, Unplug, Vercel, Webhook } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";

export function SettingsPanel(){
  const [domain,setDomain]=useState("");const [loading,setLoading]=useState(false);
  const addDomain=async()=>{if(!domain.trim())return;setLoading(true);const response=await fetch('/api/domains',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({domain,projectId:'current-project'})});const body=await response.json();response.ok?toast.success('Domain added — follow the DNS instructions'):toast.error(body.error??'Domain could not be added');setLoading(false)};
  return <div className="mt-7 grid gap-5 xl:grid-cols-[.7fr_1.3fr]"><aside><Card className="p-2">{['General','Workspace','Integrations','Domains','API keys','Security','Notifications'].map((item,index)=><button className={`flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left text-xs ${index===2?'bg-white/[.07] text-white':'text-muted-foreground hover:bg-white/[.04] hover:text-white'}`} key={item}>{item}</button>)}</Card><Card className="mt-4 border-emerald-400/10 bg-emerald-500/[.03] p-4"><div className="flex gap-3"><ShieldCheck className="size-5 text-emerald-300"/><div><h3 className="text-xs font-semibold">Security check passed</h3><p className="mt-1 text-[10px] leading-4 text-muted-foreground">Your workspace has no unresolved security recommendations.</p></div></div></Card></aside><section className="space-y-5"><Card className="p-5"><div className="flex items-start justify-between"><div><h2 className="text-sm font-semibold">Integrations</h2><p className="mt-1 text-xs text-muted-foreground">Connect the services used for source control, deployment, and assets.</p></div><Badge><Lock className="size-3"/> Encrypted</Badge></div><div className="mt-6 divide-y divide-white/[.07]">{[
    {name:'GitHub',description:'Create repositories and sync generated source code.',icon:Github,connected:false},
    {name:'Vercel',description:'Deploy projects and manage production domains.',icon:Vercel,connected:true},
    {name:'Supabase',description:'Store generated images, files, and project assets.',icon:Globe2,connected:false},
    {name:'OpenAI',description:'Power production website generations and the assistant.',icon:KeyRound,connected:true},
  ].map(item=><div className="flex flex-col gap-3 py-4 sm:flex-row sm:items-center" key={item.name}><span className="grid size-10 place-items-center rounded-xl border border-white/[.08] bg-white/[.035]"><item.icon className="size-4"/></span><div className="flex-1"><div className="flex items-center gap-2"><h3 className="text-xs font-semibold">{item.name}</h3>{item.connected&&<Badge className="border-emerald-400/15 bg-emerald-500/10 text-emerald-300"><Check className="size-3"/> Connected</Badge>}</div><p className="mt-1 text-[10px] text-muted-foreground">{item.description}</p></div><Button variant={item.connected?'ghost':'outline'} size="sm">{item.connected?<><Unplug/>Disconnect</>:<><Link2/>Connect</>}</Button></div>)}</div></Card><Card className="p-5"><h2 className="text-sm font-semibold">Custom domain</h2><p className="mt-1 text-xs text-muted-foreground">Add a domain to the currently selected production project.</p><div className="mt-5 flex flex-col gap-2 sm:flex-row"><Input value={domain} onChange={(e)=>setDomain(e.target.value)} placeholder="app.yourdomain.com"/><Button disabled={loading} onClick={addDomain}><Globe2/> Add domain</Button></div><p className="mt-3 text-[10px] text-muted-foreground">You’ll receive the exact DNS records after the domain is added.</p></Card><Card className="p-5"><div className="flex items-center justify-between"><div><h2 className="text-sm font-semibold">Webhooks</h2><p className="mt-1 text-xs text-muted-foreground">Receive signed events for generations and deployments.</p></div><Button variant="outline" size="sm"><Webhook/> Add endpoint</Button></div><div className="mt-5 rounded-xl border border-white/[.07] bg-black/15 p-3 font-mono text-[10px] text-muted-foreground">No webhook endpoints configured.</div></Card></section></div>
}
