"use client";

import { useMemo, useState } from "react";
import {
  ArrowLeft, Bot, Braces, Check, ChevronRight, Clipboard, Cloud, Code2, Copy,
  Download, ExternalLink, Github, Globe2, ImageIcon, Laptop, Lightbulb, Loader2,
  Maximize2, Monitor, Palette, Play, QrCode, Rocket, Send, Smartphone, Sparkles,
  Tablet, WandSparkles, Zap,
} from "lucide-react";
import { toast } from "sonner";
import QRCode from "qrcode";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import type { GenerationResult, GeneratorRequest, WebsiteType } from "@/lib/types";
import { cn } from "@/lib/utils";

const examplePrompt = "Create a responsive graduation project website for a hospital management system with login, analytics dashboard, patient records, appointments, about, contact, dark mode, and accessible Arabic and English layouts.";
const randomIdeas = [
  "Build a smart energy monitoring dashboard for a university graduation project with live charts, device controls, reports, and a clean green visual system.",
  "Create a premium portfolio for a software engineer with animated case studies, a GitHub activity section, skills, testimonials, and a contact form.",
  "Design a restaurant website with menu filters, table reservations, location details, customer reviews, and an elegant dark red theme.",
  "Build a school management platform landing page with student, teacher, attendance, grades, and parent portal features.",
];
const stages = [
  { label: "Analyzing request", icon: Bot, detail: "Understanding goals, audience, and requirements" },
  { label: "Planning pages", icon: Globe2, detail: "Mapping information architecture and user flows" },
  { label: "Writing code", icon: Braces, detail: "Creating typed components and application logic" },
  { label: "Generating images", icon: ImageIcon, detail: "Preparing visual assets and brand elements" },
  { label: "Optimizing SEO", icon: Zap, detail: "Improving metadata, speed, and accessibility" },
  { label: "Deploying", icon: Cloud, detail: "Packaging the production build" },
];

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block"><span className="mb-2 block text-[11px] font-medium text-muted-foreground">{label}</span>{children}</label>; }
const selectClass = "h-10 w-full rounded-xl border border-input bg-white/[.035] px-3 text-xs text-foreground outline-none focus:border-violet-500/60 focus:ring-2 focus:ring-violet-500/15";

function GenerationProgress({ active }: { active: number }) {
  return <div className="mx-auto w-full max-w-2xl py-8"><div className="relative mx-auto mb-10 grid size-24 place-items-center"><span className="absolute inset-0 animate-ping rounded-3xl border border-violet-400/30" /><span className="absolute inset-2 animate-pulse rounded-2xl bg-violet-500/10" /><WandSparkles className="relative size-8 text-violet-300" /></div><div className="text-center"><h2 className="text-xl font-semibold">Forging your website</h2><p className="mt-2 text-sm text-muted-foreground">ProjectForge is turning your brief into a production-ready project.</p></div><div className="mt-9 space-y-2">{stages.map((stage,index)=>{const done=index<active;const current=index===active;return <div className={cn("flex items-center gap-3 rounded-xl border px-4 py-3 transition",current?"border-violet-400/25 bg-violet-500/10":done?"border-emerald-400/10 bg-emerald-500/[.04]":"border-transparent opacity-45")} key={stage.label}><span className={cn("grid size-8 place-items-center rounded-lg",done?"bg-emerald-500/15 text-emerald-300":current?"bg-violet-500/15 text-violet-300":"bg-white/[.04]")}>{done?<Check className="size-4"/>:<stage.icon className={cn("size-4",current&&"animate-pulse")}/>}</span><div className="flex-1"><b className="block text-xs font-medium">{stage.label}</b><small className="text-[10px] text-muted-foreground">{stage.detail}</small></div>{current&&<Loader2 className="size-4 animate-spin text-violet-300" />}</div>})}</div><div className="mt-7 h-1.5 overflow-hidden rounded-full bg-white/[.06]"><span className="block h-full rounded-full bg-gradient-to-r from-violet-500 to-cyan-400 transition-all duration-500" style={{width:`${Math.min(((active+1)/stages.length)*100,100)}%`}} /></div></div>;
}

function ResultWorkspace({ result }: { result: GenerationResult }) {
  const [viewport, setViewport] = useState<"desktop"|"tablet"|"mobile">("desktop");
  const [tab, setTab] = useState<"preview"|"code">("preview");
  const [selectedFile, setSelectedFile] = useState(result.files[0]?.path ?? "");
  const [liveUrl, setLiveUrl] = useState(result.liveUrl);
  const [qr, setQr] = useState<string>();
  const selected = result.files.find((file)=>file.path===selectedFile) ?? result.files[0];
  const width = viewport==="desktop"?"100%":viewport==="tablet"?"768px":"390px";
  const download = async () => { const response=await fetch('/api/export',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:result.name,files:result.files})}); if(!response.ok){toast.error('Export could not be created');return} const blob=await response.blob();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`${result.name.toLowerCase().replace(/\s+/g,'-')}.zip`;a.click();URL.revokeObjectURL(url);toast.success('Project ZIP downloaded'); };
  const deploy = async () => { toast.loading('Starting deployment…',{id:'deploy'});const response=await fetch('/api/deploy',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:result.name,files:result.files})});const body=await response.json();if(!response.ok){toast.error(body.error??'Deployment needs Vercel credentials',{id:'deploy'});return}setLiveUrl(body.url);toast.success('Website is live',{id:'deploy'}); };
  const github = async () => { toast.loading('Creating repository…',{id:'github'});const response=await fetch('/api/github',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:result.name,files:result.files})});const body=await response.json();response.ok?toast.success('GitHub repository created',{id:'github'}):toast.error(body.error??'GitHub connection required',{id:'github'}); };
  const showQr = async () => { const value=liveUrl??`${location.origin}/dashboard/projects/${result.projectId}`;setQr(await QRCode.toDataURL(value,{width:260,margin:2,color:{dark:'#111827',light:'#ffffff'}})); };
  const copyLink=async()=>{await navigator.clipboard.writeText(liveUrl??location.href);toast.success('Link copied')};
  return <div className="flex min-h-[calc(100vh-4rem)] flex-col"><div className="flex flex-col gap-3 border-b border-white/[.07] px-4 py-3 lg:flex-row lg:items-center"><div className="flex min-w-0 items-center gap-3"><span className="grid size-9 place-items-center rounded-xl bg-emerald-500/10 text-emerald-300"><Check className="size-4" /></span><div className="min-w-0"><h1 className="truncate text-sm font-semibold">{result.name}</h1><p className="text-[10px] text-muted-foreground">Generated successfully · {result.files.length} files · {result.pages.length} pages</p></div></div><div className="flex flex-wrap items-center gap-2 lg:ml-auto"><Button variant="outline" size="sm" onClick={download}><Download /> Download ZIP</Button><Button variant="outline" size="sm" onClick={github}><Github /> GitHub</Button><Button variant="outline" size="sm" onClick={showQr}><QrCode /> Share</Button><Button size="sm" onClick={deploy}><Rocket /> {liveUrl?'Redeploy':'Deploy'}</Button>{liveUrl&&<Button size="icon" variant="ghost" asChild><a href={liveUrl} target="_blank" rel="noreferrer"><ExternalLink /></a></Button>}</div></div>
    <div className="flex flex-1 flex-col overflow-hidden xl:grid xl:grid-cols-[240px_1fr]">
      <aside className="hidden border-r border-white/[.07] bg-[#090910] p-3 xl:block"><div className="px-2 py-2 text-[9px] font-bold uppercase tracking-[.18em] text-muted-foreground">Project files</div><div className="mt-1 space-y-0.5">{result.files.map(file=><button onClick={()=>{setSelectedFile(file.path);setTab('code')}} className={cn("flex w-full items-center gap-2 rounded-lg px-2.5 py-2 text-left text-[11px] text-muted-foreground hover:bg-white/[.05] hover:text-white",selectedFile===file.path&&tab==='code'&&"bg-violet-500/10 text-violet-300")} key={file.path}><Code2 className="size-3" /><span className="truncate">{file.path}</span></button>)}</div><div className="mt-6 px-2 py-2 text-[9px] font-bold uppercase tracking-[.18em] text-muted-foreground">Included</div><div className="space-y-2 px-2 text-[10px] text-muted-foreground">{result.features.map(item=><p className="flex gap-2" key={item}><Check className="size-3 text-emerald-400" />{item}</p>)}</div></aside>
      <section className="flex min-w-0 flex-1 flex-col bg-[#07070d]"><div className="flex h-12 items-center border-b border-white/[.07] px-3"><div className="flex rounded-lg border border-white/[.07] p-0.5"><button onClick={()=>setTab('preview')} className={cn("rounded-md px-3 py-1.5 text-[11px]",tab==='preview'&&"bg-white/[.08] text-white")}>Preview</button><button onClick={()=>setTab('code')} className={cn("rounded-md px-3 py-1.5 text-[11px]",tab==='code'&&"bg-white/[.08] text-white")}>Code</button></div>{tab==='preview'&&<div className="ml-auto flex items-center gap-1"><Button size="icon" variant={viewport==='desktop'?'secondary':'ghost'} className="size-8" onClick={()=>setViewport('desktop')} aria-label="Desktop preview"><Monitor /></Button><Button size="icon" variant={viewport==='tablet'?'secondary':'ghost'} className="size-8" onClick={()=>setViewport('tablet')} aria-label="Tablet preview"><Tablet /></Button><Button size="icon" variant={viewport==='mobile'?'secondary':'ghost'} className="size-8" onClick={()=>setViewport('mobile')} aria-label="Mobile preview"><Smartphone /></Button><div className="mx-1 h-5 w-px bg-white/[.07]"/><Button size="icon" variant="ghost" className="size-8"><Maximize2 /></Button></div>}</div>
        {tab==='preview'?<div className="soft-scrollbar flex flex-1 justify-center overflow-auto p-3 sm:p-6"><div className="h-[calc(100vh-10rem)] overflow-hidden rounded-xl border border-white/10 bg-white shadow-2xl transition-[width] duration-300" style={{width,maxWidth:'100%'}}><iframe title="Generated website preview" sandbox="allow-forms allow-modals allow-popups" className="size-full bg-white" srcDoc={result.previewHtml} /></div></div>:<div className="flex min-h-0 flex-1 flex-col"><div className="flex h-10 items-center gap-2 border-b border-white/[.06] px-4 text-[10px] text-muted-foreground"><Code2 className="size-3" />{selected?.path}<Button onClick={()=>{navigator.clipboard.writeText(selected?.content??'');toast.success('Code copied')}} variant="ghost" size="icon" className="ml-auto size-7"><Copy /></Button></div><pre className="soft-scrollbar flex-1 overflow-auto p-5 font-mono text-[11px] leading-6 text-white/70"><code>{selected?.content}</code></pre></div>}
      </section>
    </div>{qr&&<div className="fixed inset-0 z-[70] grid place-items-center bg-black/75 p-5 backdrop-blur-sm" onClick={()=>setQr(undefined)}><div className="w-full max-w-sm rounded-2xl border border-white/10 bg-[#11111b] p-6 text-center" onClick={(e)=>e.stopPropagation()}><img src={qr} alt="Project share QR code" className="mx-auto size-56 rounded-xl bg-white p-2" /><h2 className="mt-5 font-semibold">Share this project</h2><p className="mt-1 text-xs text-muted-foreground">Scan the QR code or copy the link.</p><div className="mt-5 flex gap-2"><Button variant="outline" className="flex-1" onClick={copyLink}><Clipboard /> Copy link</Button><Button className="flex-1" onClick={()=>setQr(undefined)}>Done</Button></div></div></div>}</div>;
}

export function GeneratorStudio() {
  const [request,setRequest]=useState<GeneratorRequest>({prompt:"",websiteType:"graduation",colorTheme:"aurora",typography:"modern",framework:"nextjs",language:"english"});
  const [status,setStatus]=useState<"idle"|"generating"|"done">("idle");
  const [activeStage,setActiveStage]=useState(0);
  const [result,setResult]=useState<GenerationResult>();
  const chars=request.prompt.length;
  const update=<K extends keyof GeneratorRequest>(key:K,value:GeneratorRequest[K])=>setRequest(current=>({...current,[key]:value}));
  const generate=async()=>{if(request.prompt.trim().length<20){toast.error('Describe the website in at least 20 characters');return}setStatus('generating');setActiveStage(0);setResult(undefined);const timers=stages.slice(1).map((_,index)=>setTimeout(()=>setActiveStage(index+1),(index+1)*650));try{const response=await fetch('/api/generate',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(request)});const body=await response.json();if(!response.ok)throw new Error(body.error??'Generation failed');await new Promise(resolve=>setTimeout(resolve,Math.max(0,stages.length*650-500)));setResult(body.data);setStatus('done');}catch(error){setStatus('idle');toast.error(error instanceof Error?error.message:'Generation failed');}finally{timers.forEach(clearTimeout)}};
  const improve=()=>{if(!request.prompt.trim()){update('prompt',examplePrompt);return}update('prompt',`${request.prompt.trim()} Include a clear information architecture, accessible responsive layouts, polished micro-interactions, SEO metadata, secure forms, useful empty states, and a consistent design system.`);toast.success('Prompt improved')};
  if(status==='done'&&result)return <ResultWorkspace result={result}/>;
  if(status==='generating')return <main className="grid min-h-[calc(100vh-4rem)] place-items-center p-5"><GenerationProgress active={activeStage}/></main>;
  return <main className="p-4 sm:p-6 lg:p-8"><div className="mx-auto max-w-5xl"><div className="text-center"><Badge className="border-violet-400/20 bg-violet-400/10 text-violet-300"><Sparkles className="size-3" /> AI Website Generator</Badge><h1 className="mt-5 text-3xl font-semibold tracking-[-.04em] sm:text-5xl">What do you want to <span className="text-gradient">build today?</span></h1><p className="mx-auto mt-3 max-w-xl text-sm leading-6 text-muted-foreground">Describe the product in your own words. Add the pages, features, audience, and visual style you have in mind.</p></div><div className="gradient-border mt-10 rounded-2xl p-1"><div className="rounded-[15px] bg-card p-4 sm:p-6"><div className="flex items-center gap-2 text-xs font-medium"><WandSparkles className="size-4 text-violet-300" /> Project brief</div><Textarea autoFocus value={request.prompt} onChange={(e)=>update('prompt',e.target.value)} maxLength={5000} placeholder="Describe your project..." className="mt-4 min-h-44 border-0 bg-black/15 p-4 text-sm leading-7 shadow-inner focus:ring-1"/><div className="mt-2 flex items-center justify-between"><span className="text-[10px] text-muted-foreground">Be specific for a better result</span><span className="text-[10px] text-muted-foreground">{chars} / 5000</span></div><div className="mt-4 flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={improve}><Sparkles /> Improve prompt</Button><Button size="sm" variant="ghost" onClick={()=>update('prompt',randomIdeas[Math.floor(Math.random()*randomIdeas.length)])}><Lightbulb /> Random idea</Button><Button size="sm" variant="ghost" onClick={()=>update('prompt',examplePrompt)}><Play /> Use example</Button></div></div></div>
    <div className="mt-5 grid gap-4 rounded-2xl border border-white/[.07] bg-card p-4 sm:grid-cols-2 sm:p-6 lg:grid-cols-3"><Field label="Website type"><select className={selectClass} value={request.websiteType} onChange={(e)=>update('websiteType',e.target.value as WebsiteType)}>{['portfolio','graduation','business','ecommerce','landing','hospital','school','restaurant','company','personal'].map(type=><option key={type} value={type}>{type[0].toUpperCase()+type.slice(1).replace('ecommerce','E-commerce')}</option>)}</select></Field><Field label="Color theme"><select className={selectClass} value={request.colorTheme} onChange={(e)=>update('colorTheme',e.target.value)}><option value="aurora">Aurora violet</option><option value="ocean">Ocean blue</option><option value="forest">Forest green</option><option value="sunset">Warm sunset</option><option value="monochrome">Monochrome</option><option value="custom">Let AI decide</option></select></Field><Field label="Typography"><select className={selectClass} value={request.typography} onChange={(e)=>update('typography',e.target.value)}><option value="modern">Modern sans</option><option value="editorial">Editorial serif</option><option value="technical">Technical mono</option><option value="friendly">Friendly rounded</option></select></Field><Field label="Framework"><select className={selectClass} value={request.framework} onChange={(e)=>update('framework',e.target.value as GeneratorRequest['framework'])}><option value="nextjs">Next.js</option><option value="react">React</option><option value="html">HTML</option><option value="vue">Vue</option><option value="angular">Angular</option></select></Field><Field label="Language"><select className={selectClass} value={request.language} onChange={(e)=>update('language',e.target.value as GeneratorRequest['language'])}><option value="english">English</option><option value="arabic">Arabic</option><option value="both">Arabic + English</option></select></Field><div className="flex items-end"><div className="w-full rounded-xl border border-white/[.06] bg-white/[.025] px-3 py-2"><span className="text-[10px] text-muted-foreground">Estimated generation</span><p className="mt-0.5 text-xs font-medium">~30 seconds · 12 credits</p></div></div></div>
    <div className="mt-6 flex flex-col items-center"><Button size="lg" onClick={generate} className="min-w-60"><WandSparkles /> Generate website <ArrowLeft className="rotate-180" /></Button><p className="mt-3 flex items-center gap-1.5 text-[10px] text-muted-foreground"><Check className="size-3 text-emerald-400" /> Source code and preview are always yours</p></div></div></main>;
}
