import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, Check, Code2, Copy, ExternalLink, Github, Globe2, History, Monitor, MoreHorizontal, Rocket, Settings, Smartphone, Tablet } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { projects } from "@/lib/mock-data";

export default async function ProjectDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const project = projects.find((item) => item.id === id) ?? projects[0];
  if (!project) notFound();
  return <main><div className="flex flex-col gap-4 border-b border-white/[.07] p-4 sm:px-6 lg:flex-row lg:items-center"><div className="flex min-w-0 items-center gap-3"><Button variant="ghost" size="icon" asChild><Link href="/dashboard/projects"><ArrowLeft /></Link></Button><span className={`size-10 rounded-xl bg-gradient-to-br ${project.thumbnail}`} /><div className="min-w-0"><div className="flex items-center gap-2"><h1 className="truncate text-sm font-semibold">{project.name}</h1><Badge className="text-[9px]">{project.status}</Badge></div><p className="truncate text-[10px] text-muted-foreground">{project.description}</p></div></div><div className="flex flex-wrap gap-2 lg:ml-auto"><Button variant="outline" size="sm"><History /> Version history</Button><Button variant="outline" size="sm"><Github /> Connect GitHub</Button><Button size="sm"><Rocket /> Deploy</Button><Button variant="ghost" size="icon"><MoreHorizontal /></Button></div></div>
    <div className="grid min-h-[calc(100vh-8rem)] xl:grid-cols-[1fr_320px]"><section className="flex min-w-0 flex-col bg-[#07070d]"><div className="flex h-12 items-center gap-1 border-b border-white/[.07] px-4"><Button size="sm" variant="secondary"><Monitor /> Preview</Button><Button size="sm" variant="ghost"><Code2 /> Code</Button><div className="ml-auto flex"><Button size="icon" variant="secondary" className="size-8"><Monitor /></Button><Button size="icon" variant="ghost" className="size-8"><Tablet /></Button><Button size="icon" variant="ghost" className="size-8"><Smartphone /></Button></div></div><div className="flex flex-1 items-center justify-center p-4 sm:p-8"><div className="h-[650px] max-h-[calc(100vh-12rem)] w-full overflow-hidden rounded-xl border border-white/10 bg-white shadow-2xl"><div className="flex h-full flex-col bg-[#f7f9fc] text-slate-900"><div className="flex h-16 items-center justify-between border-b border-slate-200 bg-white px-8"><strong className="text-blue-600">{project.name}</strong><div className="flex gap-5 text-xs text-slate-500"><span>Overview</span><span>Analytics</span><span>Settings</span></div></div><div className={`flex-1 bg-gradient-to-br ${project.thumbnail} p-8`}><div className="mx-auto max-w-4xl rounded-2xl bg-white/90 p-7 shadow-2xl backdrop-blur"><p className="text-xs text-slate-500">Project overview</p><h2 className="mt-2 text-3xl font-semibold">Welcome back</h2><div className="mt-7 grid grid-cols-3 gap-3">{[['Total users','2,481'],['Active now','384'],['Success rate','98.4%']].map(([label,value])=><div className="rounded-xl border border-slate-200 bg-white p-4" key={label}><span className="text-[10px] text-slate-500">{label}</span><b className="mt-2 block text-2xl">{value}</b></div>)}</div><div className="mt-4 h-40 rounded-xl border border-slate-200 bg-slate-50 p-4"><div className="flex h-full items-end gap-2">{[30,55,42,72,64,88,70,96,78,82,94,74].map((h,i)=><i className="flex-1 rounded-t bg-blue-500/60" style={{height:`${h}%`}} key={i}/>)}</div></div></div></div></div></div></div></section>
      <aside className="border-l border-white/[.07] bg-card p-5"><h2 className="text-sm font-semibold">Project details</h2><dl className="mt-5 space-y-4 text-xs">{[['Framework',project.framework],['Last generated','Version 7'],['Pages','8 pages'],['Components','34 components'],['Visibility','Private']].map(([label,value])=><div className="flex justify-between" key={label}><dt className="text-muted-foreground">{label}</dt><dd>{value}</dd></div>)}</dl><div className="mt-6 border-t border-white/[.07] pt-5"><h3 className="text-xs font-semibold">Production</h3>{project.liveUrl?<div className="mt-3 rounded-xl border border-emerald-400/15 bg-emerald-500/[.05] p-3"><div className="flex items-center gap-2 text-xs text-emerald-300"><Check className="size-3.5" /> Live and healthy</div><a href={project.liveUrl} className="mt-2 flex items-center gap-1 truncate text-[10px] text-muted-foreground">{project.liveUrl}<ExternalLink className="size-3" /></a></div>:<div className="mt-3 rounded-xl border border-white/[.07] bg-white/[.025] p-3 text-xs text-muted-foreground">This project has not been deployed yet.</div>}<Button className="mt-3 w-full" size="sm"><Rocket /> Deploy latest version</Button></div><div className="mt-6 border-t border-white/[.07] pt-5"><h3 className="text-xs font-semibold">Recent changes</h3><div className="mt-4 space-y-4">{['Updated dashboard cards','Improved mobile navigation','Generated contact page'].map((item,index)=><div className="flex gap-2.5" key={item}><span className="mt-1 size-2 rounded-full bg-violet-400"/><div><p className="text-[11px]">{item}</p><small className="text-[9px] text-muted-foreground">{index+1} {index?'days':'hour'} ago</small></div></div>)}</div></div></aside></div>
  </main>;
}
