import Link from "next/link";
import { ArrowRight, Eye, Search, Sparkles } from "lucide-react";
import { PageHeader } from "@/components/dashboard/page-header";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { templates } from "@/lib/mock-data";

export default function TemplatesPage() {
  return <main className="p-4 sm:p-6 lg:p-8"><PageHeader title="Template marketplace" description="Start from proven structures and make them entirely yours." badge="Curated by ProjectForge" /><div className="mt-7 flex flex-col justify-between gap-3 sm:flex-row"><div className="relative w-full max-w-md"><Search className="absolute left-3 top-3.5 size-3.5 text-muted-foreground" /><Input className="pl-9" placeholder="Search templates..." /></div><div className="soft-scrollbar flex gap-2 overflow-x-auto pb-1">{['All','Graduation','Portfolio','Business','E-commerce','Education'].map((item,index)=><Button size="sm" variant={index===0?'secondary':'ghost'} key={item}>{item}</Button>)}</div></div><div className="mt-6 grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{templates.map(template=><article className="group overflow-hidden rounded-2xl border border-white/[.08] bg-card" key={template.id}><div className={`relative h-52 overflow-hidden bg-gradient-to-br ${template.color}`}><div className="absolute inset-6 translate-y-3 rounded-xl border border-white/20 bg-background/75 p-4 shadow-2xl backdrop-blur-xl transition duration-500 group-hover:translate-y-0"><div className="flex gap-1"><i className="size-1.5 rounded-full bg-white/30" /><i className="size-1.5 rounded-full bg-white/30" /><i className="size-1.5 rounded-full bg-white/30" /></div><div className="mt-5 h-4 w-1/2 rounded bg-white/15" /><div className="mt-3 h-2 w-4/5 rounded bg-white/10" /><div className="mt-8 grid grid-cols-3 gap-2"><i className="h-16 rounded-lg bg-white/10" /><i className="h-16 rounded-lg bg-white/10" /><i className="h-16 rounded-lg bg-white/10" /></div></div><div className="absolute inset-0 flex items-center justify-center bg-black/45 opacity-0 transition group-hover:opacity-100"><Button variant="secondary"><Eye /> Preview</Button></div></div><div className="p-5"><div className="flex justify-between"><Badge>{template.category}</Badge><span className="text-[10px] text-muted-foreground">{template.uses} uses</span></div><h2 className="mt-4 font-semibold">{template.name}</h2><p className="mt-1.5 text-xs text-muted-foreground">{template.description}</p><div className="mt-5 flex items-center justify-between border-t border-white/[.06] pt-4"><span className="text-[10px] text-muted-foreground">{template.pages} pages included</span><Button size="sm" asChild><Link href={`/dashboard/generate?template=${template.id}`}><Sparkles /> Use template</Link></Button></div></div></article>)}</div></main>;
}
