import { Check, CircleAlert, Clock3, ExternalLink, Globe2, MoreHorizontal, Rocket } from "lucide-react";
import { PageHeader } from "@/components/dashboard/page-header";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";

const deployments=[
  {project:'HealthOS Dashboard',url:'healthos-demo.vercel.app',branch:'main',commit:'a18d03f',status:'Ready',time:'12 minutes ago',duration:'34s'},
  {project:'FinFlow',url:'finflow-demo.vercel.app',branch:'main',commit:'6de4c1a',status:'Ready',time:'Yesterday',duration:'28s'},
  {project:'EcoTrack',url:'ecotrack-preview.vercel.app',branch:'preview',commit:'b781f20',status:'Building',time:'2 minutes ago',duration:'—'},
  {project:'Creative Portfolio',url:'portfolio-preview.vercel.app',branch:'main',commit:'0410fcb',status:'Error',time:'3 days ago',duration:'16s'},
];

export default function DeploymentsPage(){return <main className="p-4 sm:p-6 lg:p-8"><PageHeader title="Deployments" description="Monitor production and preview builds across every project." actions={<Button><Rocket/> New deployment</Button>}/><section className="mt-7 grid gap-3 sm:grid-cols-3">{[['Production sites','8',Globe2,'text-emerald-300 bg-emerald-500/10'],['Builds this month','24',Rocket,'text-violet-300 bg-violet-500/10'],['Average build','31s',Clock3,'text-cyan-300 bg-cyan-500/10']].map(([label,value,Icon,tone])=><Card className="p-5" key={label as string}><div className="flex items-center justify-between"><div><strong className="text-2xl">{value as string}</strong><p className="mt-1 text-xs text-muted-foreground">{label as string}</p></div><span className={`grid size-10 place-items-center rounded-xl ${tone}`}><Icon className="size-4"/></span></div></Card>)}</section><Card className="mt-6 overflow-hidden"><div className="flex items-center justify-between border-b p-5"><div><h2 className="text-sm font-semibold">Recent deployments</h2><p className="mt-1 text-[10px] text-muted-foreground">Production and preview environments</p></div><Button variant="outline" size="sm">All environments</Button></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-xs"><thead className="border-b border-white/[.06] text-[10px] uppercase tracking-wider text-muted-foreground"><tr><th className="px-5 py-3 font-medium">Project</th><th className="px-5 py-3 font-medium">Status</th><th className="px-5 py-3 font-medium">Source</th><th className="px-5 py-3 font-medium">Duration</th><th className="px-5 py-3 font-medium">Created</th><th/></tr></thead><tbody className="divide-y divide-white/[.06]">{deployments.map(item=><tr className="hover:bg-white/[.02]" key={item.url}><td className="px-5 py-4"><b className="block font-medium">{item.project}</b><a href={`https://${item.url}`} className="mt-1 flex items-center gap-1 text-[10px] text-muted-foreground">{item.url}<ExternalLink className="size-3"/></a></td><td className="px-5 py-4"><Badge className={item.status==='Ready'?'border-emerald-400/15 bg-emerald-500/10 text-emerald-300':item.status==='Building'?'border-amber-400/15 bg-amber-500/10 text-amber-300':'border-red-400/15 bg-red-500/10 text-red-300'}>{item.status==='Ready'?<Check/>:item.status==='Building'?<Clock3/>:<CircleAlert/>}{item.status}</Badge></td><td className="px-5 py-4"><span>{item.branch}</span><code className="ml-2 text-[10px] text-muted-foreground">{item.commit}</code></td><td className="px-5 py-4 text-muted-foreground">{item.duration}</td><td className="px-5 py-4 text-muted-foreground">{item.time}</td><td className="px-5 py-4"><Button variant="ghost" size="icon" className="size-8"><MoreHorizontal/></Button></td></tr>)}</tbody></table></div></Card></main>}
